-- MySQL Script generated by MySQL Workbench
-- Wed Jan 31 17:57:14 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema aquaponics
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `aquaponics` ;

-- -----------------------------------------------------
-- Schema aquaponics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aquaponics` DEFAULT CHARACTER SET utf8 ;
USE `aquaponics` ;

-- -----------------------------------------------------
-- Table `aquaponics`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aquaponics`.`users` ;

CREATE TABLE IF NOT EXISTS `aquaponics`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `mi` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `contactnumber` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aquaponics`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aquaponics`.`roles` ;

CREATE TABLE IF NOT EXISTS `aquaponics`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aquaponics`.`logins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aquaponics`.`logins` ;

CREATE TABLE IF NOT EXISTS `aquaponics`.`logins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NULL,
  `password` VARCHAR(100) NULL,
  `roles_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`, `roles_id`, `users_id`),
  INDEX `fk_logins_roles_idx` (`roles_id` ASC),
  INDEX `fk_logins_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_logins_roles`
    FOREIGN KEY (`roles_id`)
    REFERENCES `aquaponics`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logins_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `aquaponics`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aquaponics`.`types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aquaponics`.`types` ;

CREATE TABLE IF NOT EXISTS `aquaponics`.`types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL COMMENT '1 - plant\n2 - fish',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aquaponics`.`kinds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aquaponics`.`kinds` ;

CREATE TABLE IF NOT EXISTS `aquaponics`.`kinds` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `types_id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `modified` DATETIME NULL,
  `created` DATETIME NULL,
  PRIMARY KEY (`id`, `types_id`),
  INDEX `fk_kinds_initialtypes1_idx` (`types_id` ASC),
  CONSTRAINT `fk_kinds_initialtypes1`
    FOREIGN KEY (`types_id`)
    REFERENCES `aquaponics`.`types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aquaponics`.`initials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aquaponics`.`initials` ;

CREATE TABLE IF NOT EXISTS `aquaponics`.`initials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` VARCHAR(45) NULL,
  `unitprice` VARCHAR(45) NULL,
  `kinds_id` INT NOT NULL,
  `kinds_initialtypes_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`, `kinds_id`, `kinds_initialtypes_id`, `users_id`),
  INDEX `fk_initials_kinds1_idx` (`kinds_id` ASC, `kinds_initialtypes_id` ASC),
  INDEX `fk_initials_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_initials_kinds1`
    FOREIGN KEY (`kinds_id` , `kinds_initialtypes_id`)
    REFERENCES `aquaponics`.`kinds` (`id` , `types_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_initials_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `aquaponics`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aquaponics`.`inifinals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aquaponics`.`inifinals` ;

CREATE TABLE IF NOT EXISTS `aquaponics`.`inifinals` (
  `id` INT(11) NOT NULL,
  `quantity` VARCHAR(45) NULL,
  `unitprice` VARCHAR(45) NULL,
  `initials_id` INT(11) NOT NULL,
  `initials_kinds_id` INT(11) NOT NULL,
  `initials_kinds_initialtypes_id` INT(11) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_finals_initials1_idx` (`initials_id` ASC, `initials_kinds_id` ASC, `initials_kinds_initialtypes_id` ASC),
  CONSTRAINT `fk_finals_initials1`
    FOREIGN KEY (`initials_id` , `initials_kinds_id` , `initials_kinds_initialtypes_id`)
    REFERENCES `aquaponics`.`initials` (`id` , `kinds_id` , `kinds_initialtypes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aquaponics`.`ponds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aquaponics`.`ponds` ;

CREATE TABLE IF NOT EXISTS `aquaponics`.`ponds` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `users_id` INT NOT NULL,
  `pondscol` VARCHAR(45) NULL,
  `phlevel` DECIMAL(10,2) NULL,
  `templevel` DECIMAL(10,2) NULL,
  `turblevel` DECIMAL(10,2) NULL,
  `waterlevel` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_ponds_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_ponds_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `aquaponics`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
